apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domain-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: vpd-domain-api.lab.local.ctoaas.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: domain-api
                port:
                  name: http
  tls:
    - hosts:
        - vpd-domain-api.lab.local.ctoaas.co
      secretName: domain-api-lab-local-ctoaas-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excise-mock
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: excise-mock-vpd.lab.local.ctoaas.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: excise-mock
                port:
                  name: http
  tls:
    - hosts:
        - excise-mock-vpd.lab.local.ctoaas.co
      secretName: excise-mock-lab-local-ctoaas-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-mock
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: customer-mock-vpd.lab.local.ctoaas.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-mock
                port:
                  name: http
  tls:
    - hosts:
        - customer-mock-vpd.lab.local.ctoaas.co
      secretName: customer-mock-lab-local-ctoaas-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tax-platform-mock
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: tax-platform-mock-vpd.lab.local.ctoaas.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tax-platform-mock
                port:
                  name: http
  tls:
    - hosts:
        - tax-platform-mock-vpd.lab.local.ctoaas.co
      secretName: tax-platform-mock-lab-local-ctoaas-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpd-docs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: vpd-docs.lab.local.ctoaas.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  name: http
  tls:
    - hosts:
        - vpd-docs.lab.local.ctoaas.co
      secretName: vpd-docs-lab-local-ctoaas-tls
