plugins {
    id 'groovy'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:4.0.29'
    implementation 'org.apache.groovy:groovy-json:4.0.29'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

sourceSets {
    main {
        groovy { srcDirs = ['src'] }
    }
    test {
        groovy { 
            srcDirs = ['test']
            srcDirs += ['/common/src', '../common/src']
        }
    }
}

test {
    useJUnitPlatform()
}
