extends: ["spectral:oas"]

# Note: Using default spectral:oas rules. Custom severity overrides for built-in rules
# have been removed as they may not exist in all Spectral versions.

rules:
  # Disable example validation for XML content - XML examples are string literals
  # which is valid per OpenAPI spec but Spectral expects objects
  oas3-valid-media-example: off
  # Custom rules for this project
  uk-tax-domain-naming:
    description: Ensure UK tax domain terminology is used consistently
    message: "{{description}}"
    severity: warn
    given: "$.paths.*.*"
    then:
      - field: summary
        function: truthy
      - field: description
        function: truthy

  relationship-links-present:
    description: Resources should include _links for relationships
    message: "Response schemas should include _links field for hypermedia navigation"
    severity: warn
    given: "$.components.schemas[?(@.type == 'object')]"
    then:
      field: properties._links
      function: truthy

  cross-api-absolute-urls:
    description: Cross-API relationship links should use absolute URLs
    message: "Relationship links should use absolute URLs with full scheme and host"
    severity: info
    given: "$.components.schemas..properties._links"
    then:
      function: truthy
