version: '3'

vars:
  SPECS_DIR: specs
  DOCS_DIR: docs
  TESTS_DIR: tests

tasks:
  # Validation tasks
  validate:
    desc: Validate all OpenAPI specifications
    cmds:
      - npx @redocly/cli lint {{.SPECS_DIR}}/taxpayer/taxpayer-api.yaml
      - npx @redocly/cli lint {{.SPECS_DIR}}/income-tax/income-tax-api.yaml
      - npx @redocly/cli lint {{.SPECS_DIR}}/payment/payment-api.yaml
      - npx @redocly/cli lint {{.SPECS_DIR}}/shared/shared-components.yaml

  validate:taxpayer:
    desc: Validate Taxpayer API specification
    cmds:
      - npx @redocly/cli lint {{.SPECS_DIR}}/taxpayer/taxpayer-api.yaml

  validate:income-tax:
    desc: Validate Income Tax API specification
    cmds:
      - npx @redocly/cli lint {{.SPECS_DIR}}/income-tax/income-tax-api.yaml

  validate:payment:
    desc: Validate Payment API specification
    cmds:
      - npx @redocly/cli lint {{.SPECS_DIR}}/payment/payment-api.yaml

  # Linting tasks
  lint:
    desc: Lint all OpenAPI specifications with Spectral
    cmds:
      - npx spectral lint {{.SPECS_DIR}}/**/*.yaml

  # Mock server tasks
  mock:
    desc: Start all mock servers concurrently
    cmds:
      - npx concurrently "task mock:taxpayer" "task mock:income-tax" "task mock:payment"

  mock:taxpayer:
    desc: Start Taxpayer API mock server on port 8081
    cmds:
      - npx prism mock {{.SPECS_DIR}}/taxpayer/taxpayer-api.yaml -p 8081

  mock:income-tax:
    desc: Start Income Tax API mock server on port 8082
    cmds:
      - npx prism mock {{.SPECS_DIR}}/income-tax/income-tax-api.yaml -p 8082

  mock:payment:
    desc: Start Payment API mock server on port 8083
    cmds:
      - npx prism mock {{.SPECS_DIR}}/payment/payment-api.yaml -p 8083

  # Documentation generation tasks
  docs:
    desc: Generate documentation for all APIs
    cmds:
      - task docs:taxpayer
      - task docs:income-tax
      - task docs:payment
      - task docs:copy-specs

  docs:copy-specs:
    desc: Copy OpenAPI specs to docs folder for explorer
    cmds:
      - mkdir -p {{.DOCS_DIR}}/specs/taxpayer
      - mkdir -p {{.DOCS_DIR}}/specs/income-tax
      - mkdir -p {{.DOCS_DIR}}/specs/payment
      - mkdir -p {{.DOCS_DIR}}/specs/shared
      - cp {{.SPECS_DIR}}/taxpayer/taxpayer-api.yaml {{.DOCS_DIR}}/specs/taxpayer/
      - cp {{.SPECS_DIR}}/income-tax/income-tax-api.yaml {{.DOCS_DIR}}/specs/income-tax/
      - cp {{.SPECS_DIR}}/payment/payment-api.yaml {{.DOCS_DIR}}/specs/payment/
      - cp {{.SPECS_DIR}}/shared/shared-components.yaml {{.DOCS_DIR}}/specs/shared/

  docs:taxpayer:
    desc: Generate Taxpayer API documentation
    cmds:
      - mkdir -p {{.DOCS_DIR}}/taxpayer
      - npx @redocly/cli build-docs {{.SPECS_DIR}}/taxpayer/taxpayer-api.yaml -o {{.DOCS_DIR}}/taxpayer/index.html

  docs:income-tax:
    desc: Generate Income Tax API documentation
    cmds:
      - mkdir -p {{.DOCS_DIR}}/income-tax
      - npx @redocly/cli build-docs {{.SPECS_DIR}}/income-tax/income-tax-api.yaml -o {{.DOCS_DIR}}/income-tax/index.html

  docs:payment:
    desc: Generate Payment API documentation
    cmds:
      - mkdir -p {{.DOCS_DIR}}/payment
      - npx @redocly/cli build-docs {{.SPECS_DIR}}/payment/payment-api.yaml -o {{.DOCS_DIR}}/payment/index.html

  # Documentation server
  docs:serve:
    desc: Serve API documentation on http://localhost:8080
    cmds:
      - echo "Starting documentation server at http://localhost:8080"
      - echo "Press Ctrl+C to stop the server"
      - docker-compose up docs

  # Start everything - LocalStack + mock APIs
  start:
    desc: Start LocalStack and all backend mock servers
    cmds:
      - echo "Starting Domain API POC with LocalStack..."
      - docker-compose up -d
      - echo "Waiting for services to be ready..."
      - sleep 5
      - task: gateway:init
      - echo ""
      - echo "=== Services Started ==="
      - echo "Documentation - http://localhost:8080"
      - echo "Taxpayer API - http://localhost:8081"
      - echo "Income Tax API - http://localhost:8082"
      - echo "Payment API - http://localhost:8083"
      - echo "API Gateway - See output above for URL"
      - echo ""
      - echo "Run 'task gateway:test' to test the APIs"
      - echo "Run 'task stop' to stop all services"

  stop:
    desc: Stop all services
    cmds:
      - echo "Stopping all services..."
      - docker-compose down -v

  # Swagger UI
  swagger:
    desc: Open Swagger UI for Taxpayer API (use swagger:taxpayer, swagger:income-tax, swagger:payment for individual APIs)
    cmds:
      - npx swagger-ui-watcher {{.SPECS_DIR}}/taxpayer/taxpayer-api.yaml

  swagger:taxpayer:
    desc: Open Swagger UI for Taxpayer API on port 8000
    cmds:
      - npx swagger-ui-watcher {{.SPECS_DIR}}/taxpayer/taxpayer-api.yaml -p 8000

  swagger:income-tax:
    desc: Open Swagger UI for Income Tax API on port 8001
    cmds:
      - npx swagger-ui-watcher {{.SPECS_DIR}}/income-tax/income-tax-api.yaml -p 8001

  swagger:payment:
    desc: Open Swagger UI for Payment API on port 8002
    cmds:
      - npx swagger-ui-watcher {{.SPECS_DIR}}/payment/payment-api.yaml -p 8002

  swagger:all:
    desc: Open Swagger UI for all APIs in separate browser tabs (ports 8000-8002)
    cmds:
      - npx concurrently "task swagger:taxpayer" "task swagger:income-tax" "task swagger:payment"

  # Testing tasks
  test:
    desc: Run all tests
    cmds:
      - npm run test

  test:unit:
    desc: Run unit tests
    cmds:
      - npm run test:unit

  test:property:
    desc: Run property-based tests
    cmds:
      - npm run test:property

  test:integration:
    desc: Run integration tests
    cmds:
      - npm run test:integration

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - npm run test:watch

  test:acceptance:
    desc: Run acceptance tests
    cmds:
      - cd {{.TESTS_DIR}}/acceptance && npm test

  test:acceptance:headed:
    desc: Run acceptance tests in headed mode (see browser)
    cmds:
      - cd {{.TESTS_DIR}}/acceptance && npm run test:headed

  test:acceptance:ui:
    desc: Run acceptance tests in UI mode (interactive)
    cmds:
      - cd {{.TESTS_DIR}}/acceptance && npm run test:ui

  test:acceptance:install:
    desc: Install acceptance test dependencies and Playwright browsers
    cmds:
      - cd {{.TESTS_DIR}}/acceptance && npm install
      - cd {{.TESTS_DIR}}/acceptance && npx playwright install

  test:acceptance:report:
    desc: View acceptance test report
    cmds:
      - cd {{.TESTS_DIR}}/acceptance && npm run report

  test:acceptance:skipped:
    desc: Run only the slow/skipped acceptance tests (Swagger UI rendering tests)
    cmds:
      - cd {{.TESTS_DIR}}/acceptance && npm run test:skipped

  test:acceptance:skipped:headed:
    desc: Run slow/skipped acceptance tests in headed mode
    cmds:
      - cd {{.TESTS_DIR}}/acceptance && npm run test:skipped:headed

  # Installation
  install:
    desc: Install dependencies
    cmds:
      - npm install

  # Clean tasks
  clean:
    desc: Clean generated files
    cmds:
      - rm -rf {{.DOCS_DIR}}/taxpayer
      - rm -rf {{.DOCS_DIR}}/income-tax
      - rm -rf {{.DOCS_DIR}}/payment
      - rm -rf node_modules
      - rm -rf coverage

  # Gateway management tasks
  gateway:init:
    desc: Initialize API Gateway and Lambda in LocalStack
    cmds:
      - echo "Initializing API Gateway and Lambda..."
      - docker-compose exec -T localstack /tools/localstack-init.sh

  gateway:logs:
    desc: View gateway logs
    cmds:
      - docker-compose logs -f localstack

  gateway:logs:taxpayer:
    desc: View Taxpayer API logs
    cmds:
      - docker-compose logs -f taxpayer-api

  gateway:logs:income-tax:
    desc: View Income Tax API logs
    cmds:
      - docker-compose logs -f income-tax-api

  gateway:logs:payment:
    desc: View Payment API logs
    cmds:
      - docker-compose logs -f payment-api

  gateway:status:
    desc: Check gateway and backend API status
    cmds:
      - echo "=== Docker Services Status ==="
      - docker-compose ps
      - echo ""
      - echo "=== LocalStack API Gateway ==="
      - docker-compose exec -T localstack awslocal apigateway get-rest-apis 2>/dev/null || echo "LocalStack not running or not initialized"
      - echo ""
      - echo "=== Backend API Health ==="
      - echo "Taxpayer API (port 8081):"
      - 'curl -s -o /dev/null -w "  Status: %{http_code}\n" http://localhost:8081 || echo "  Not accessible"'
      - echo "Income Tax API (port 8082):"
      - 'curl -s -o /dev/null -w "  Status: %{http_code}\n" http://localhost:8082 || echo "  Not accessible"'
      - echo "Payment API (port 8083):"
      - 'curl -s -o /dev/null -w "  Status: %{http_code}\n" http://localhost:8083 || echo "  Not accessible"'

  gateway:test:
    desc: Test gateway aggregation
    cmds:
      - echo "=== Testing Direct API Access ==="
      - echo "Taxpayer API:"
      - curl -s http://localhost:8081/taxpayers/TP123456 | jq . || echo "Failed"
      - echo ""
      - echo "Income Tax API:"
      - curl -s "http://localhost:8082/tax-returns?taxpayerId=TP123456" | jq . || echo "Failed"
      - echo ""
      - echo "Payment API:"
      - curl -s "http://localhost:8083/payments?taxpayerId=TP123456" | jq . || echo "Failed"
      - echo ""
      - echo "=== Testing Gateway Access (Custom Domain) ==="
      - echo "Gateway (without include):"
      - curl -s "http://domain-api.execute-api.localhost.localstack.cloud:4566/dev/taxpayers/TP123456" | jq . || echo "Failed"
      - echo ""
      - echo "Gateway (with include parameter):"
      - curl -s "http://domain-api.execute-api.localhost.localstack.cloud:4566/dev/taxpayers/TP123456?include=taxReturns" | jq . || echo "Failed"

  gateway:restart:
    desc: Restart all gateway services
    cmds:
      - task: gateway:stop
      - task: gateway:start

  gateway:clean:
    desc: Stop and remove all containers, networks, and volumes
    cmds:
      - echo "Cleaning up all gateway resources..."
      - docker-compose down -v
      - echo "✓ Cleanup complete"

  # Lambda management tasks
  lambda:install:
    desc: Install Lambda dependencies
    dir: gateway/lambda
    cmds:
      - npm install

  lambda:build:
    desc: Build aggregation Lambda function
    dir: gateway/lambda
    cmds:
      - npm run build

  lambda:package:
    desc: Build and package Lambda function for deployment
    dir: gateway/lambda
    cmds:
      - npm run package

  lambda:deploy:
    desc: Deploy Lambda to LocalStack
    deps: [lambda:package]
    cmds:
      - echo "Deploying Lambda to LocalStack..."
      - docker cp gateway/lambda/aggregation-lambda.zip domain-api-localstack:/tmp/
      - docker-compose exec -T localstack awslocal lambda update-function-code --function-name aggregation-lambda --zip-file fileb:///tmp/aggregation-lambda.zip
      - echo "✓ Lambda deployed successfully"

  lambda:logs:
    desc: View Lambda logs
    cmds:
      - docker-compose exec -T localstack awslocal logs tail /aws/lambda/aggregation-lambda --follow

  lambda:test:
    desc: Run Lambda unit tests
    dir: gateway/lambda
    cmds:
      - npm test

  lambda:clean:
    desc: Clean Lambda build artifacts
    dir: gateway/lambda
    cmds:
      - npm run clean
      - rm -f aggregation-lambda.zip

  # Acceptance test tasks
  test:acceptance:
    desc: Run all acceptance tests (UI and Gateway)
    cmds:
      - task: test:acceptance:ui:all
      - task: test:acceptance:gateway

  test:acceptance:ui:all:
    desc: Run all UI acceptance tests
    dir: tests/acceptance/ui
    cmds:
      - npm test

  test:acceptance:headed:
    desc: Run UI acceptance tests in headed mode
    dir: tests/acceptance/ui
    cmds:
      - npm run test:headed

  test:acceptance:ui:
    desc: Run UI acceptance tests in UI mode (interactive)
    dir: tests/acceptance/ui
    cmds:
      - npm run test:ui

  test:acceptance:gateway:
    desc: Run gateway API acceptance tests
    dir: tests/acceptance/gateway
    cmds:
      - npm test

  test:acceptance:explorer:
    desc: Run API explorer acceptance tests
    dir: tests/acceptance/ui
    cmds:
      - npm run test:explorer

  test:acceptance:docs:
    desc: Run documentation site acceptance tests
    dir: tests/acceptance/ui
    cmds:
      - npm run test:docs

  test:acceptance:skipped:
    desc: Run slow acceptance tests (Swagger UI rendering)
    dir: tests/acceptance/ui
    cmds:
      - npm run test:skipped

  test:acceptance:skipped:headed:
    desc: Run slow acceptance tests in headed mode
    dir: tests/acceptance/ui
    cmds:
      - npm run test:skipped:headed

  test:acceptance:report:
    desc: View acceptance test report
    dir: tests/acceptance/ui
    cmds:
      - npm run report

  # Status check
  status:
    desc: Show project status
    cmds:
      - echo "=== OpenAPI Specifications ==="
      - ls -lh {{.SPECS_DIR}}/taxpayer/taxpayer-api.yaml
      - ls -lh {{.SPECS_DIR}}/income-tax/income-tax-api.yaml
      - ls -lh {{.SPECS_DIR}}/payment/payment-api.yaml
      - ls -lh {{.SPECS_DIR}}/shared/shared-components.yaml
      - echo ""
      - echo "=== Documentation ==="
      - ls -lh {{.DOCS_DIR}}/ 2>/dev/null || echo "No documentation generated yet"
      - echo ""
      - echo "=== Tests ==="
      - npm run test 2>&1 | head -20 || echo "Run 'task test' to execute tests"
      - echo ""
      - echo "=== Gateway Status ==="
      - task: gateway:status
