openapi: 3.0.3
info:
  title: Domain API Gateway
  version: 1.0.0
  description: |
    API Gateway for the Domain API POC. This gateway provides cross-API aggregation
    capabilities and supports three content negotiation modes:
    
    1. **Aggregated Mode** (default): Process includes and return enriched responses
    2. **Simple REST Mode**: Return standard JSON without aggregation
    3. **Pass-Through Mode**: Return raw backend responses without transformation
    
    The gateway routes requests to three backend APIs:
    - Taxpayer API
    - Income Tax API
    - Payment API

servers:
  - url: http://domain-api.execute-api.localhost.localstack.cloud:4566/dev
    description: LocalStack development gateway
  - url: http://localhost:4566/restapis/{apiId}/dev/_user_request_
    description: LocalStack direct API Gateway URL
    variables:
      apiId:
        default: domain-api
        description: API Gateway ID

paths:
  /{proxy+}:
    parameters:
      - name: proxy+
        in: path
        required: true
        schema:
          type: string
        description: Proxy path to backend API (e.g., taxpayers/TP123456)
      - name: include
        in: query
        required: false
        schema:
          type: string
        description: |
          Comma-separated list of relationships to include in the response.
          Only processed in aggregated mode (default or Accept: application/vnd.domain+json).
          Ignored in simple REST mode (Accept: application/json) and pass-through mode (Accept: application/vnd.raw).
        example: taxReturns,payments
    
    get:
      summary: Proxy GET request to backend API
      description: |
        Routes GET requests to the appropriate backend API based on the path.
        Supports three content negotiation modes via Accept header:
        
        - **application/vnd.domain+json** (default): Aggregated mode with includes
        - **application/json**: Simple REST mode without aggregation
        - **application/vnd.raw**: Pass-through mode, raw backend response
      parameters:
        - name: Accept
          in: header
          required: false
          schema:
            type: string
            enum:
              - application/vnd.domain+json
              - application/json
              - application/vnd.raw
            default: application/vnd.domain+json
          description: |
            Content negotiation header to select gateway mode:
            - `application/vnd.domain+json` (default): Aggregated mode with includes
            - `application/json`: Simple REST mode without aggregation
            - `application/vnd.raw`: Pass-through mode, raw backend response
      responses:
        '200':
          description: Successful response
          content:
            application/vnd.domain+json:
              schema:
                $ref: '#/components/schemas/AggregatedResponse'
              examples:
                taxpayerWithIncludes:
                  summary: Taxpayer with included tax returns
                  value:
                    id: TP123456
                    type: taxpayer
                    nino: AB123456C
                    name:
                      firstName: John
                      lastName: Smith
                    _links:
                      self:
                        href: /dev/taxpayers/TP123456
                      taxReturns:
                        href: /dev/tax-returns?taxpayerId=TP123456
                        type: collection
                    _included:
                      taxReturns:
                        - id: TR20230001
                          type: tax-return
                          taxpayerId: TP123456
                          taxYear: 2023-24
                          status: assessed
                          _links:
                            self:
                              href: /dev/tax-returns/TR20230001
                taxpayerWithoutIncludes:
                  summary: Taxpayer without includes
                  value:
                    id: TP123456
                    type: taxpayer
                    nino: AB123456C
                    name:
                      firstName: John
                      lastName: Smith
                    _links:
                      self:
                        href: /dev/taxpayers/TP123456
                      taxReturns:
                        href: /dev/tax-returns?taxpayerId=TP123456
                        type: collection
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleRestResponse'
              examples:
                taxpayer:
                  summary: Taxpayer in simple REST mode
                  value:
                    id: TP123456
                    type: taxpayer
                    nino: AB123456C
                    name:
                      firstName: John
                      lastName: Smith
                    _links:
                      self:
                        href: /dev/taxpayers/TP123456
                      taxReturns:
                        href: /dev/tax-returns?taxpayerId=TP123456
                        type: collection
            application/vnd.raw:
              schema:
                type: object
                description: Raw backend response without transformation
              examples:
                taxpayerRaw:
                  summary: Raw backend response
                  value:
                    id: TP123456
                    type: taxpayer
                    nino: AB123456C
                    name:
                      firstName: John
                      lastName: Smith
                    _links:
                      self:
                        href: /taxpayers/TP123456
                      taxReturns:
                        href: /tax-returns?taxpayerId=TP123456
                        type: collection
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Gateway error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Proxy POST request to backend API
      description: Routes POST requests to the appropriate backend API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Resource created
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Gateway error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      summary: Proxy PUT request to backend API
      description: Routes PUT requests to the appropriate backend API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Resource updated
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Gateway error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    patch:
      summary: Proxy PATCH request to backend API
      description: Routes PATCH requests to the appropriate backend API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Resource updated
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Gateway error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Proxy DELETE request to backend API
      description: Routes DELETE requests to the appropriate backend API
      responses:
        '204':
          description: Resource deleted
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Gateway error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    options:
      summary: CORS preflight request
      description: Handles CORS preflight requests
      responses:
        '200':
          description: CORS headers
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string

components:
  schemas:
    AggregatedResponse:
      type: object
      description: Response in aggregated mode with optional _included section
      properties:
        id:
          type: string
        type:
          type: string
        _links:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: object
                properties:
                  href:
                    type: string
                  type:
                    type: string
                  title:
                    type: string
        _included:
          type: object
          description: Included related resources
          additionalProperties:
            type: array
            items:
              type: object
      additionalProperties: true
    
    SimpleRestResponse:
      type: object
      description: Response in simple REST mode without _included section
      properties:
        id:
          type: string
        type:
          type: string
        _links:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: object
                properties:
                  href:
                    type: string
                  type:
                    type: string
                  title:
                    type: string
      additionalProperties: true
    
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: string

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true

x-amazon-apigateway-gateway-responses:
  DEFAULT_4XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,Accept'"
  DEFAULT_5XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,Accept'"
