# Quarkus Camel configuration
quarkus.http.port=8080

# Enable Camel YAML DSL
camel.main.routes-include-pattern=camel/*.yaml

# Enable Kamelet discovery
camel.component.kamelet.location=classpath:/kamelets
