openapi: 3.0.3
info:
  title: VPD Submission Returns API
  version: 1.0.0
  description: 'Domain API for Vaping Products Duty (VPD) Submission Returns.


    **Producer OAS**: This specification defines the core domain contract.

    Platform features (sparse fieldsets, rate limiting, correlation) are

    automatically added by the platform.



    ---


    **Platform-Enhanced OAS**: This specification includes platform features automatically injected for
    all HIP APIs (sparse fieldsets, rate limiting, correlation IDs).'
  x-platform-generated: true
  x-platform-features:
    sparseFieldsets: true
    rateLimiting: true
    correlationId: true
    etags: true
servers:
- url: http://localhost:4566
  description: Local Development (Docker)
- url: https://api.hip.hmrc.gov.uk
  description: Production
- url: https://api.qa.hip.hmrc.gov.uk
  description: QA
tags:
- name: Submission Returns
  description: VPD submission return operations
paths:
  /duty/vpd/submission-returns/v1:
    post:
      tags:
      - Submission Returns
      summary: Submit a VPD return
      description: 'Submit a new VPD return. The domain API orchestrates:

        1. excise: Validates submission and calculates duty/VAT

        2. Parallel: tax-platform stores + customer enriches response


        Returns acknowledgement reference and ETag for optimistic locking.

        '
      operationId: submitReturn
      parameters:
      - $ref: ../fragments/headers/v1/oas.yaml#/X-Correlation-Id-Header
      - $ref: ../fragments/headers/v1/oas.yaml#/X-Idempotency-Key-Header
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmissionRequest'
            examples:
              validSubmission:
                $ref: '#/components/examples/ValidSubmissionRequest'
      responses:
        '201':
          description: Submission accepted and stored
          headers:
            X-Correlation-Id:
              $ref: ../fragments/headers/v1/oas.yaml#/X-Correlation-Id-Response
            ETag:
              $ref: ../fragments/headers/v1/oas.yaml#/ETag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionResponse'
              examples:
                success:
                  $ref: '#/components/examples/SubmissionSuccessResponse'
        '400':
          $ref: ../fragments/responses/v1/oas.yaml#/BadRequest
        '401':
          $ref: ../fragments/responses/v1/oas.yaml#/Unauthorized
        '403':
          $ref: ../fragments/responses/v1/oas.yaml#/Forbidden
        '404':
          $ref: ../fragments/responses/v1/oas.yaml#/NotFound
        '409':
          $ref: ../fragments/responses/v1/oas.yaml#/Conflict
        '422':
          $ref: ../fragments/responses/v1/oas.yaml#/ValidationError
        '429':
          $ref: ../fragments/responses/v1/oas.yaml#/TooManyRequests
        '500':
          $ref: ../fragments/responses/v1/oas.yaml#/InternalServerError
        '503':
          $ref: ../fragments/responses/v1/oas.yaml#/ServiceUnavailable
    get:
      tags:
      - Submission Returns
      summary: Retrieve a VPD return
      description: 'Retrieve a VPD return by acknowledgement reference OR by approval number + period.

        Response includes enriched trader details from customer system.


        **Platform Feature**: Sparse fieldsets are automatically supported via

        `fields[:submission]=field1,field2` query parameter.



        **Platform Feature**: Sparse fieldsets automatically supported. See `fields` parameter below.'
      operationId: getReturn
      parameters:
      - $ref: ../fragments/headers/v1/oas.yaml#/X-Correlation-Id-Header
      - $ref: '#/components/parameters/acknowledgementReference'
      - $ref: '#/components/parameters/vpdApprovalNumber'
      - $ref: '#/components/parameters/periodKey'
      - name: fields
        in: query
        description: '**Platform-provided sparse fieldsets.** Request specific fields from the response.


          Format: `fields[:submission]=field1,field2,field3`


          Multiple fields are comma-separated. Invalid field names return 400.


          **Available fields**: acknowledgementReference, basicInformation, calculations, period, periodKey,
          status, storedAt, trader, vpdApprovalNumber, warnings'
        required: false
        schema:
          type: string
          pattern: ^fields\[:submission\]=([\w]+,?)+$
        examples:
          singleField:
            summary: Request single field
            value: fields[:submission]=period
          multipleFields:
            summary: Request multiple fields
            value: fields[:submission]=period,periodKey,calculations
      responses:
        '200':
          description: Submission found
          headers:
            X-Correlation-Id:
              $ref: ../fragments/headers/v1/oas.yaml#/X-Correlation-Id-Response
            ETag:
              $ref: ../fragments/headers/v1/oas.yaml#/ETag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrichedSubmission'
              examples:
                full:
                  $ref: '#/components/examples/EnrichedSubmissionResponse'
        '400':
          $ref: ../fragments/responses/v1/oas.yaml#/BadRequest
        '401':
          $ref: ../fragments/responses/v1/oas.yaml#/Unauthorized
        '403':
          $ref: ../fragments/responses/v1/oas.yaml#/Forbidden
        '404':
          $ref: ../fragments/responses/v1/oas.yaml#/NotFound
        '429':
          $ref: ../fragments/responses/v1/oas.yaml#/TooManyRequests
        '500':
          $ref: ../fragments/responses/v1/oas.yaml#/InternalServerError
        '503':
          $ref: ../fragments/responses/v1/oas.yaml#/ServiceUnavailable
components:
  parameters:
    acknowledgementReference:
      name: acknowledgementReference
      in: query
      description: Acknowledgement reference from submission (mutually exclusive with vpdApprovalNumber+periodKey)
      schema:
        type: string
        pattern: ^ACK-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}$
        example: ACK-2026-01-27-000123
      required: false
    vpdApprovalNumber:
      name: vpdApprovalNumber
      in: query
      description: VPD approval number (requires periodKey)
      schema:
        type: string
        pattern: ^VPD[0-9]{6}$
        example: VPD123456
      required: false
    periodKey:
      name: periodKey
      in: query
      description: Period key (requires vpdApprovalNumber)
      schema:
        $ref: ../fragments/schemas/v1/oas.yaml#/PeriodKey
      required: false
  schemas:
    SubmissionRequest:
      type: object
      required:
      - vpdApprovalNumber
      - periodKey
      - basicInformation
      properties:
        vpdApprovalNumber:
          type: string
          pattern: ^VPD[0-9]{6}$
          description: VPD approval number
          example: VPD123456
        periodKey:
          $ref: ../fragments/schemas/v1/oas.yaml#/PeriodKey
        basicInformation:
          $ref: '#/components/schemas/BasicInformation'
        dutyProducts:
          type: array
          description: List of duty products in this return
          items:
            $ref: '#/components/schemas/DutyProduct'
    BasicInformation:
      type: object
      required:
      - returnType
      - submittedBy
      properties:
        returnType:
          type: string
          enum:
          - ORIGINAL
          - AMENDMENT
          description: Type of return
        submittedBy:
          type: object
          required:
          - type
          - name
          properties:
            type:
              type: string
              enum:
              - ORG
              - INDIVIDUAL
            name:
              type: string
              minLength: 1
              maxLength: 255
              example: Example Vapes Ltd
    DutyProduct:
      type: object
      description: Duty product details (placeholder for POC)
      properties:
        productCode:
          type: string
        quantity:
          type: number
          minimum: 0
        dutyRate:
          type: number
          minimum: 0
    SubmissionResponse:
      type: object
      required:
      - acknowledgementReference
      - vpdApprovalNumber
      - periodKey
      - status
      - storedAt
      properties:
        acknowledgementReference:
          type: string
          description: Unique acknowledgement reference
          pattern: ^ACK-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}$
          example: ACK-2026-01-27-000123
        vpdApprovalNumber:
          type: string
          pattern: ^VPD[0-9]{6}$
          example: VPD123456
        periodKey:
          $ref: ../fragments/schemas/v1/oas.yaml#/PeriodKey
        status:
          type: string
          enum:
          - RECEIVED
          - VALIDATED
          - REJECTED
          description: Processing status
          example: RECEIVED
        storedAt:
          $ref: ../fragments/schemas/v1/oas.yaml#/Timestamp
        warnings:
          type: array
          description: Non-blocking validation warnings
          items:
            $ref: '#/components/schemas/Warning'
    EnrichedSubmission:
      allOf:
      - $ref: '#/components/schemas/SubmissionResponse'
      - type: object
        properties:
          basicInformation:
            $ref: '#/components/schemas/BasicInformation'
          trader:
            type: object
            description: Enriched trader details from customer system
            properties:
              name:
                type: string
                example: Example Vapes Ltd
              type:
                type: string
                enum:
                - ORG
                - INDIVIDUAL
              registeredAddress:
                $ref: ../fragments/schemas/v1/oas.yaml#/Address
          calculations:
            type: object
            description: Duty and VAT calculations from excise
            properties:
              totalDutyDue:
                $ref: ../fragments/schemas/v1/oas.yaml#/Money
              vat:
                $ref: ../fragments/schemas/v1/oas.yaml#/Money
          period:
            type: object
            description: Period context from excise
            properties:
              key:
                $ref: ../fragments/schemas/v1/oas.yaml#/PeriodKey
              startDate:
                type: string
                format: date
                example: '2024-01-01'
              endDate:
                type: string
                format: date
                example: '2024-03-31'
              state:
                type: string
                enum:
                - OPEN
                - FILED
                - CLOSED
                description: 'OPEN - Period is open for filing

                  FILED - Returns filed but period still open for amendments

                  CLOSED - Period closed, no further changes allowed

                  '
                example: OPEN
    Warning:
      type: object
      required:
      - code
      - text
      properties:
        code:
          type: string
          description: Warning code
          example: WARN-VD-001
        text:
          type: string
          description: Human-readable warning message
          example: Spoilt product close to upper threshold
        path:
          type: string
          description: JSON path to the field (optional)
          example: /dutyProducts/0/quantity
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth 2.0 bearer token (platform-provided authentication)
  examples:
    ValidSubmissionRequest:
      summary: Valid submission request
      value:
        vpdApprovalNumber: VPD123456
        periodKey: 24A1
        basicInformation:
          returnType: ORIGINAL
          submittedBy:
            type: ORG
            name: Example Vapes Ltd
        dutyProducts: []
    SubmissionSuccessResponse:
      summary: Successful submission
      value:
        acknowledgementReference: ACK-2026-01-27-000123
        vpdApprovalNumber: VPD123456
        periodKey: 24A1
        status: RECEIVED
        storedAt: '2026-01-27T14:51:02Z'
        warnings: []
    EnrichedSubmissionResponse:
      summary: Enriched submission with trader and period details
      value:
        acknowledgementReference: ACK-2026-01-27-000123
        vpdApprovalNumber: VPD123456
        periodKey: 24A1
        status: RECEIVED
        storedAt: '2026-01-27T14:51:02Z'
        basicInformation:
          returnType: ORIGINAL
          submittedBy:
            type: ORG
            name: Example Vapes Ltd
        trader:
          name: Example Vapes Ltd
          type: ORG
          registeredAddress:
            line1: 123 High Street
            city: London
            postcode: AB1 2CD
            country: GB
        calculations:
          totalDutyDue:
            amount: 12345.67
            currency: GBP
          vat:
            amount: 2469.13
            currency: GBP
        period:
          key: 24A1
          startDate: '2024-01-01'
          endDate: '2024-03-31'
          state: OPEN
        warnings: []
security:
- BearerAuth: []
