services:
  kamelet-routeid-test:
    image: apache/camel-jbang:4.16.0
    container_name: kamelet-routeid-test
    command: >
      run /routes/routes-customer-routeid.yaml
          /routes/shared-customer.kamelet.yaml
          --dep=org.apache.camel:camel-groovy
          --dep=org.apache.groovy:groovy-json:4.0.29
    ports:
      - "8093:8080"
    volumes:
      - .:/routes:ro
    networks:
      - domain-api-network

networks:
  domain-api-network:
    external: true
    name: domain-apis_domain-api-network
