---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-agents-domain-apis
  labels:
    drive: agents
    target-namespace: domain-apis
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.32.163
    path: /rpool/data/k8s/agents
  mountOptions:
    - nfsvers=4.2
    - noatime
  claimRef:
    name: workspace-agents
    namespace: domain-apis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-agents
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: workspace-agents-domain-apis
