apiVersion: v1
kind: Service
metadata:
  name: docs
  labels:
    app.kubernetes.io/name: docs
    app.kubernetes.io/component: docs
spec:
  selector:
    app.kubernetes.io/name: docs
  ports:
    - name: http
      port: 8080
      targetPort: 8080
