openapi: 3.0.3
info:
  title: Excise Duty System API - VPD
  version: 1.0.0
  description: |
    Backend API for Excise Duty System managing VPD registrations, periods,
    and duty calculations.

    **System of Record For:**
    - VPD registrations (vpdApprovalNumber → customerId mapping)
    - Period definitions and state
    - Duty calculation rules and validation

    **Content Type:** This legacy system returns XML responses.
    The Domain API transforms XML→JSON for unified API responses.

servers:
  - url: http://localhost:4010
    description: Local mock server
  - url: http://excise-mock:4010
    description: Docker internal
  - url: https://excise.internal.hmrc.gov.uk
    description: Internal production

tags:
  - name: Registrations
    description: VPD registration operations
  - name: Periods
    description: Period operations
  - name: Validation
    description: Submission validation and calculation

paths:
  /excise/vpd/registrations/{vpdApprovalNumber}:
    get:
      tags:
        - Registrations
      summary: Get VPD registration
      description: |
        Returns VPD registration details including the customerId mapping
        and approval status.

        **Response Format:** XML (legacy system)
      operationId: getRegistration
      parameters:
        - name: vpdApprovalNumber
          in: path
          required: true
          schema:
            type: string
            example: "VPD123456"
      responses:
        '200':
          description: Registration found
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Registration'
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <registration>
                  <vpdApprovalNumber>VPD123456</vpdApprovalNumber>
                  <customerId>CUST789</customerId>
                  <status>ACTIVE</status>
                  <registeredDate>2023-06-15</registeredDate>
                </registration>
        '404':
          description: Registration not found
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <error>
                  <code>NOT_FOUND</code>
                  <message>VPD approval number not found</message>
                </error>

  /excise/vpd/periods/{periodKey}:
    get:
      tags:
        - Periods
      summary: Get period definition
      description: |
        Returns period definition including dates, duty rates, and current state.

        **Response Format:** XML (legacy system)
      operationId: getPeriod
      parameters:
        - name: periodKey
          in: path
          required: true
          schema:
            type: string
            example: "24A1"
      responses:
        '200':
          description: Period found
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Period'
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <period>
                  <periodKey>24A1</periodKey>
                  <startDate>2024-01-01</startDate>
                  <endDate>2024-03-31</endDate>
                  <state>OPEN</state>
                  <dutyRates>
                    <standardRate>0.15</standardRate>
                    <reducedRate>0.075</reducedRate>
                  </dutyRates>
                </period>
        '404':
          description: Period not found
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <error>
                  <code>NOT_FOUND</code>
                  <message>Period not found</message>
                </error>

  /excise/vpd/validate-and-calculate:
    post:
      tags:
        - Validation
      summary: Validate submission and calculate duty
      description: |
        Validates a VPD submission against business rules and calculates
        duty and VAT totals. Returns customerId for downstream enrichment.

        **Request Format:** JSON
        **Response Format:** XML (legacy system)

        **Validation includes:**
        - VPD approval number is active and valid
        - Period is in OPEN state
        - Submission payload meets business rules
        - Duty products are valid

        **Calculation includes:**
        - Total duty due
        - VAT calculations
        - Calculation hash for idempotency verification
      operationId: validateAndCalculate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationRequest'
            examples:
              valid:
                $ref: '#/components/examples/ValidValidationRequest'
      responses:
        '200':
          description: Validation and calculation complete
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
              examples:
                valid:
                  summary: Validation passed
                  value: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <validationResult>
                      <valid>true</valid>
                      <customerId>CUST789</customerId>
                      <calculations>
                        <totalDutyDue currency="GBP">12345.67</totalDutyDue>
                        <vat rate="0.20">2469.13</vat>
                        <calculationHash>sha256:abc123def456</calculationHash>
                      </calculations>
                      <warnings>
                        <warning code="WARN-VD-001">Spoilt product close to upper threshold</warning>
                      </warnings>
                      <errors/>
                    </validationResult>
                invalid:
                  summary: Validation failed
                  value: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <validationResult>
                      <valid>false</valid>
                      <customerId>CUST789</customerId>
                      <calculations/>
                      <warnings/>
                      <errors>
                        <error code="ERR-VD-002" path="/dutyProducts/0/quantity">Duty product quantity must be greater than zero</error>
                      </errors>
                    </validationResult>
        '400':
          description: Malformed request
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <error>
                  <code>BAD_REQUEST</code>
                  <message>Malformed request body</message>
                </error>
        '404':
          description: Approval number or period not found
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <error>
                  <code>NOT_FOUND</code>
                  <message>VPD approval number or period not found</message>
                </error>
        '409':
          description: Period already filed or not in OPEN state
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <error>
                  <code>CONFLICT</code>
                  <message>Period is not in OPEN state</message>
                </error>
        '422':
          description: Validation failed - business rule violations
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <validationResult>
                  <valid>false</valid>
                  <customerId>CUST789</customerId>
                  <calculations/>
                  <warnings/>
                  <errors>
                    <error code="ERR-VD-003" path="/submission/basicInformation">Missing required field: returnType</error>
                  </errors>
                </validationResult>

components:
  schemas:
    Registration:
      type: object
      xml:
        name: registration
      required:
        - vpdApprovalNumber
        - customerId
        - status
        - registeredDate
      properties:
        vpdApprovalNumber:
          type: string
          xml:
            name: vpdApprovalNumber
          example: "VPD123456"
        customerId:
          type: string
          description: Customer ID in customer system
          xml:
            name: customerId
          example: "CUST789"
        status:
          type: string
          enum: [ACTIVE, SUSPENDED, REVOKED]
          xml:
            name: status
          example: "ACTIVE"
        registeredDate:
          type: string
          format: date
          xml:
            name: registeredDate
          example: "2023-06-15"

    Period:
      type: object
      xml:
        name: period
      required:
        - periodKey
        - startDate
        - endDate
        - state
      properties:
        periodKey:
          type: string
          xml:
            name: periodKey
          example: "24A1"
        startDate:
          type: string
          format: date
          xml:
            name: startDate
          example: "2024-01-01"
        endDate:
          type: string
          format: date
          xml:
            name: endDate
          example: "2024-03-31"
        state:
          type: string
          enum: [OPEN, FILED, CLOSED]
          xml:
            name: state
          description: |
            OPEN - Period is open for filing
            FILED - Returns filed but period still open for amendments
            CLOSED - Period closed, no further changes allowed
          example: "OPEN"
        dutyRates:
          type: object
          xml:
            name: dutyRates
          description: Duty rates for this period
          properties:
            standardRate:
              type: number
              xml:
                name: standardRate
            reducedRate:
              type: number
              xml:
                name: reducedRate

    ValidationRequest:
      type: object
      description: JSON request body (not XML)
      required:
        - vpdApprovalNumber
        - periodKey
        - submission
      properties:
        vpdApprovalNumber:
          type: string
          example: "VPD123456"
        periodKey:
          type: string
          example: "24A1"
        submission:
          type: object
          description: Full submission payload to validate
          properties:
            basicInformation:
              type: object
            dutyProducts:
              type: array
              items:
                type: object

    ValidationResponse:
      type: object
      xml:
        name: validationResult
      required:
        - valid
        - customerId
      properties:
        valid:
          type: boolean
          xml:
            name: valid
          description: True if validation passed
          example: true
        customerId:
          type: string
          xml:
            name: customerId
          description: Customer ID from registration (for downstream enrichment)
          example: "CUST789"
        calculations:
          type: object
          xml:
            name: calculations
          description: Calculated duty and VAT (only present if valid=true)
          properties:
            totalDutyDue:
              type: number
              xml:
                name: totalDutyDue
                attribute: false
              description: Total duty amount with currency attribute
            vat:
              type: number
              xml:
                name: vat
                attribute: false
              description: VAT amount with rate attribute
            calculationHash:
              type: string
              xml:
                name: calculationHash
              description: Hash of calculation inputs for idempotency verification
              example: "sha256:abc123def456"
        warnings:
          type: array
          xml:
            name: warnings
            wrapped: true
          description: Non-blocking warnings
          items:
            type: object
            xml:
              name: warning
            properties:
              code:
                type: string
                xml:
                  attribute: true
              text:
                type: string
        errors:
          type: array
          xml:
            name: errors
            wrapped: true
          description: Validation errors (only present if valid=false)
          items:
            type: object
            xml:
              name: error
            properties:
              code:
                type: string
                xml:
                  attribute: true
              path:
                type: string
                xml:
                  attribute: true
              text:
                type: string

    Error:
      type: object
      xml:
        name: error
      required:
        - code
        - message
      properties:
        code:
          type: string
          xml:
            name: code
          example: "NOT_FOUND"
        message:
          type: string
          xml:
            name: message
          example: "VPD approval number not found"

  examples:
    ValidValidationRequest:
      summary: Valid validation request
      value:
        vpdApprovalNumber: "VPD123456"
        periodKey: "24A1"
        submission:
          basicInformation:
            returnType: "ORIGINAL"
            submittedBy:
              type: "ORG"
              name: "Example Vapes Ltd"
          dutyProducts: []
